<a href="https://colab.research.google.com/github/sankalpgp/T170800517_TSNIF_AIML/blob/sankalpgp%2Fv/TNS_Day_5_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



## 🧹 Data Cleaning & Preprocessing

---

### 🎯 Objective:
Learn how to clean, preprocess, and prepare data before applying Machine Learning models.

---

### ⚠️ Why this matters?
Garbage Data ❌ → Garbage Output ❌  
Clean Data ✅ → Better Models ✅

In [ ]:
import pandas as pd
import numpy as np

## 🔹 What is Data Cleaning?

Data Cleaning is the process of:
- Fixing incorrect data
- Handling missing values
- Removing duplicates
- Standardizing formats

---

## 🔹 Why is Data Preprocessing Important?

Machine Learning models:
- Cannot handle missing or messy data properly
- Require numerical and consistent input

---

## 🔹 Example of Messy Data:

| Name | Age | City     |
|------|-----|----------|
| Ram  | 25  | Mumbai   |
| Shyam| NaN | mumbai   |
| Ram  | 25  | Mumbai   |

Problems:
- Missing values
- Inconsistent text
- Duplicate rows

In [ ]:
data = {
    "Name": ["Ram", "Shyam", "Ram", "Sita", None,"Shyam","Shyam","Shyam","Ram"],
    "Age": [25, np.nan, 25, 30, 22,13,17,18,19],
    "City": ["Mumbai", "mumbai", "Mumbai", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi"]
}
print(data)
df = pd.DataFrame(data)
df

{'Name': ['Ram', 'Shyam', 'Ram', 'Sita', None, 'Shyam', 'Shyam', 'Shyam', 'Ram'], 'Age': [25, nan, 25, 30, 22, 13, 17, 18, 19], 'City': ['Mumbai', 'mumbai', 'Mumbai', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi']}

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

## 🔹 Common Data Issues

1. Missing Values → NaN
2. Duplicate Records
3. Incorrect Data Types
4. Inconsistent Text (Mumbai vs mumbai)

---

We must identify and fix these issues before using data.

In [ ]:
# First few rows
print(df.head())

# Data info
df.info()

# Summary statistics
df.describe()

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      float64
 2   City    9 non-null      object
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes

            Age
count   8.00000
mean   21.12500
std     5.43632
min    13.00000
25%    17.75000
50%    20.50000
75%    25.00000
max    30.00000

## 🔹 Missing Values

Missing values are represented as:
- NaN (Not a Number)
- None

---

## 🔍 Steps:
1. Identify missing values
2. Count them
3. Decide:
   - Drop
   - Fill

In [ ]:
# Check missing values
df.isnull()

# Count missing values
df.isnull().sum()

Name    1
Age     1
City    0
dtype: int64

In [ ]:
# Drop rows with missing values
df_drop = df.dropna()
df_drop

    Name   Age    City
0    Ram  25.0  Mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

## 🔹 Filling Missing Values

### Numerical Columns:
- Mean
- Median

### Categorical Columns:
- Mode

---

## 🧠 When to Use:
- Mean → Normal data
- Median → Skewed data
- Mode → Categories

In [ ]:
# ✅ Best Practice

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])


df

    Name     Age    City
0    Ram  25.000  Mumbai
1  Shyam  21.125  mumbai
2    Ram  25.000  Mumbai
3   Sita  30.000   Delhi
4  Shyam  22.000   Delhi
5  Shyam  13.000   Delhi
6  Shyam  17.000   Delhi
7  Shyam  18.000   Delhi
8    Ram  19.000   Delhi

## 🔹 Selecting Multiple Columns

To work on multiple columns together:

### ✅ Syntax:
df[["col1", "col2"]]

---

## 🔹 Why use this?
- Apply same operation on multiple columns
- Clean multiple columns at once
- Save time and avoid repetition

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Nashik", "Delhi", "Pune", "Akola","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Nashik
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0   Akola
4  20.0  20000.0  Mumbai

In [ ]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Nashik
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0   Akola
4  20.00  20000.0  Mumbai

In [ ]:
# Convert multiple columns to integer

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

df.dtypes
df

   Age  Salary    City
0   20   20000  Nashik
1   23   25000   Delhi
2   25   26250    Pune
3   30   40000   Akola
4   20   20000  Mumbai

In [ ]:
# Increase values by 10%

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0  Mumbai

In [ ]:
df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0  Mumbai

In [ ]:
# Replace specific values

df[["City"]] = df[["City"]].replace("Mumbai", "Pune")

df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

In [ ]:
df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

## 🔹 Encoding (Categorical → Numerical)

Machine Learning models only understand numbers.

---

### Types of Data:
1. Nominal → No order (City, Color)
2. Ordinal → Ordered (Low, Medium, High)

---

### Methods:
- One-Hot Encoding
- Label Encoding

In [ ]:
df_encoded = pd.get_dummies(df, columns=["City"])
df_encoded

    Age   Salary  City_Akola  City_Delhi  City_Mumbai  City_Nashik  City_Pune
0  22.0  22000.0       False       False        False         True      False
1  25.3  27500.0       False        True        False        False      False
2  27.5  28875.0       False       False        False        False       True
3  33.0  44000.0        True       False        False        False      False
4  22.0  22000.0       False       False         True        False      False

## 🔹 Label Encoding (Concept)

Converts categories into numbers:

Example:
Mumbai → 0  
Delhi → 1  

⚠️ Not ideal for nominal data (creates fake order)

## 🔹 Duplicate Records

Duplicate data can:
- Bias model
- Reduce accuracy

---

### Solution:
Use drop_duplicates()

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0  Mumbai

In [ ]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()
#FEMALE female Female FeMale
df2

    Age   Salary    City
0  22.0  22000.0  NASHIK
1  25.3  27500.0   DELHI
2  27.5  28875.0    PUNE
3  33.0  44000.0   AKOLA
4  22.0  22000.0  MUMBAI

In [ ]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
df2

   Age   Salary    City
0   22  22000.0  NASHIK
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0   AKOLA
4   22  22000.0  MUMBAI

# 🌧️ Rainfall Dataset Cleaning

## 🎯 Objective:
Clean and preprocess the dataset `rainfall.csv`

---

## 🔹 Dataset Columns:
- date
- rainfall
- temperature
- humidity
- wind_speed
- weather_condition

---

## ⚠️ Possible Issues:
- Date format not parsed
- Missing values (if any)
- Inconsistent text (Rainy / rainy)
- Wrong data types
- Outliers

---

## ✅ Steps We Will Perform:
1. Load dataset
2. Convert date column
3. Handle missing values
4. Fix text inconsistencies
5. Remove duplicates
6. Detect & handle outliers
7. Final clean dataset

## 📤 Upload CSV File from Local System (Google Colab)

Since the file is on your computer, we need to upload it manually.

---

## 🔹 Steps:
1. Run the cell below
2. Click "Choose Files"
3. Select `rainfall.csv`
4. File will be uploaded to Colab environment

---

After uploading, we can load it using pandas.

In [ ]:
from google.colab import files

uploaded = files.upload()

In [ ]:
# Check uploaded file name
file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

Uploaded file: rainfall.csv

In [ ]:
import pandas as pd

# Load the uploaded file
df = pd.read_csv(file_name)

df.head()

         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2022-01-01      12.5         15.2      78.0         8.5             Rainy
1  2022-01-02       8.2         17.8      65.0         5.2             Rainy
2  2022-01-03       0.0         20.1      52.0         3.1             Sunny
3  2022-01-04       3.7         18.6      71.0         6.7             Rainy
4  2022-01-05      21.1         14.8      82.0         9.3             Rainy

## 🔧 Data Cleaning Operations on rainfall.csv

After uploading and loading the dataset, we perform:

---

### ✅ Operations:
1. Inspect data
2. Convert date column
3. Handle missing values
4. Fix text inconsistencies
5. Remove duplicates
6. Handle outliers
7. Feature engineering
8. Encoding categorical data
9. Save cleaned dataset

---

Each step is important for ML readiness.

In [ ]:
df.head()

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               54 non-null     object
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB

date                 0
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

## 🔹 Convert Date Column

Convert string → datetime format

---

Helps in:
- Sorting
- Time-based analysis

In [ ]:
df["date"] = df["date"].astype(str).str.strip()
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               53 non-null     datetime64[ns]
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 2.7+ KB

## 🔹 Handle Missing Values

### Numerical Columns:
- rainfall
- temperature
- humidity
- wind_speed

➡️ Fill with mean

### Categorical:
- weather_condition

➡️ Fill with mode

In [ ]:
import pandas as pd

# Numerical columns
num_cols = ["rainfall", "temperature", "humidity", "wind_speed"]

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical missing values with mode
df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0])

# Check missing values
print(df.isnull().sum())

date                 1
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

## 🔹 Fix Text Inconsistency

Standardize text:
- Rainy → rainy
- SUNNY → sunny

In [ ]:
df["weather_condition"] = df["weather_condition"].str.lower()

df["weather_condition"].unique()

df.head()

        date  rainfall  temperature  humidity  wind_speed weather_condition
0 2022-01-01      12.5         15.2      78.0         8.5             rainy
1 2022-01-02       8.2         17.8      65.0         5.2             rainy
2 2022-01-03       0.0         20.1      52.0         3.1             sunny
3 2022-01-04       3.7         18.6      71.0         6.7             rainy
4 2022-01-05      21.1         14.8      82.0         9.3             rainy

In [ ]:
df.to_csv("cleaned_rainfall.csv", index=False)

# Download
files.download("cleaned_rainfall.csv")

In [ ]:
import pandas as pd
from google.colab import files

# Convert to Excel
df.to_excel("cleaned_rainfall.xlsx", index=False)

# Download
files.download("cleaned_rainfall.xlsx")

# 🎓 Student Performance Dataset – Data Cleaning

## 🎯 Objective:
Clean and preprocess student dataset for ML

---

## 🔹 Columns:
- name
- age
- gender
- marks
- attendance
- city

---

## ⚠️ Possible Issues:
- Missing values
- Inconsistent text (Male / male)
- Invalid marks (>100 or <0)
- Duplicates

In [ ]:
import pandas as pd
import numpy as np

data = {
    "name": ["Amit", "Sara", "John", "Amit", None],
    "age": [20, 21, np.nan, 20, 19],
    "gender": ["Male", "female", "Male", "Male", "FEMALE"],
    "marks": [85, 90, 105, 85, -5],
    "attendance": [90, 85, 80, 90, None],
    "city": ["Mumbai", "Delhi", "mumbai", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

   name   age  gender  marks  attendance    city
0  Amit  20.0    Male     85        90.0  Mumbai
1  Sara  21.0  female     90        85.0   Delhi
2  John   NaN    Male    105        80.0  mumbai
3  Amit  20.0    Male     85        90.0  Mumbai
4  None  19.0  FEMALE     -5         NaN    Pune

In [ ]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         4 non-null      float64
 2   gender      5 non-null      object
 3   marks       5 non-null      int64
 4   attendance  4 non-null      float64
 5   city        5 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 372.0+ bytes

             age       marks  attendance
count   4.000000    5.000000    4.000000
mean   20.000000   72.000000   86.250000
std     0.816497   43.817805    4.787136
min    19.000000   -5.000000   80.000000
25%    19.750000   85.000000   83.750000
50%    20.000000   85.000000   87.500000
75%    20.250000   90.000000   90.000000
max    21.000000  105.000000   90.000000

## 🔹 Handling Missing Values

- age → mean
- attendance → mean
- name → "Unknown"

In [ ]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["attendance"].fillna(df["attendance"].mean(), inplace=True)
df["name"].fillna("Unknown", inplace=True)

df

In [ ]:
df["gender"] = df["gender"].str.lower()
df["city"] = df["city"].str.lower()

df

## 🔹 Fix Invalid Data

Marks should be:
- Between 0 and 100

In [ ]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]

df

## 🔹 Basic Questions

1. Load a CSV file and display:
   - First 5 rows
   - Last 5 rows

2. Find:
   - Total number of rows & columns
   - Data types of each column

3. Identify missing values:
   - Which columns have missing values?
   - Count them

4. Fill missing values:
   - Numerical → mean
   - Categorical → mode

5. Remove duplicate rows

6. Convert a column:
   - "date" → datetime format

7. Rename columns:
   - Change column names to lowercase

8. Change data type:
   - Convert float → int (where applicable)

## 🔹 Intermediate Questions

1. Select multiple columns and:
   - Fill missing values together

2. Apply transformation:
   - Increase salary/marks by 10%

3. Fix inconsistent text:
   - "Mumbai", "mumbai", "MUMBAI" → one format

4. Create new column:
   - Example: "Pass/Fail" based on marks

5. Filter data:
   - Students with marks > 80
   - Rainfall > 10

6. Drop unnecessary columns:
   - Based on relevance

7. Apply One-Hot Encoding:
   - On categorical columns

8. Sort dataset:
   - Based on date or marks

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("data.csv")

### 1. Load CSV and Display First & Last 5 Rows

In [ ]:
# Display first 5 rows
print("First 5 rows:")
display(df.head())

# Display last 5 rows
print("Last 5 rows:")
display(df.tail())

First 5 rows:

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating
0,1,22,28000,Male,NaN,2026-01-05,1250,1,4.2
1,2,25,35000,Female,NaN,2026-01-12,2100,2,NaN
2,3,29,48000,Male,Bangalore,2026-01-20,3500,5,4.1
3,4,31,55000,Female,Delhi,2026-02-02,4200,7,4.7
4,5,27,42000,Male,Hyderabad,2026-02-10,2750,4,3.9

Last 5 rows:

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating
15,16,23,29000,Female,Pune,2026-05-06,1450,1,NaN
16,17,40,90000,Male,Chennai,2026-05-14,8300,15,4.5
17,18,32,61000,Female,Bangalore,2026-05-22,4600,8,4.2
18,19,48,125000,Male,Delhi,2026-06-01,15000,23,4.8
19,20,27,44000,Female,Nashik,2026-06-09,2900,4,NaN

### 2. Rows, Columns, and Data Types

In [ ]:
print(f"Total Rows: {df.shape[0]}, Total Columns: {df.shape[1]}\n")
print("Data types of each column:")
print(df.dtypes)

Total Rows: 20, Total Columns: 9

Data types of each column:
ID                   int64
Age                  int64
Salary               int64
Gender              object
City                object
Date                object
Purchase_Amount      int64
Experience           int64
Rating             float64
dtype: object

### 3. Identify and Count Missing Values

In [ ]:
missing_counts = df.isnull().sum()
print("Missing values per column:")
print(missing_counts[missing_counts > 0])

Missing values per column:
Gender    2
City      2
Rating    5
dtype: int64

### 4. Fill Missing Values (Numerical -> Mean, Categorical -> Mode)

In [ ]:
for col in df.columns:
    if df[col].isnull().any():
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(df[col].mean())
        else:
            df[col] = df[col].fillna(df[col].mode()[0])

print("Remaining missing values:")
print(df.isnull().sum())

Remaining missing values:
ID                 0
Age                0
Salary             0
Gender             0
City               0
Date               0
Purchase_Amount    0
Experience         0
Rating             0
dtype: int64

### 5. Remove Duplicate Rows

In [ ]:
initial_rows = df.shape[0]
df = df.drop_duplicates()
print(f"Removed {initial_rows - df.shape[0]} duplicate rows.")

Removed 0 duplicate rows.

### 6. Convert 'Date' Column to Datetime Format

In [ ]:
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    print("Date column converted to:", df['Date'].dtype)
elif 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'], errors='coerce')
    print("date column converted to:", df['date'].dtype)

Date column converted to: datetime64[ns]

### 7. Rename Columns to Lowercase

In [ ]:
df.columns = df.columns.str.lower()
print("New columns list:", df.columns.tolist())

New columns list: ['id', 'age', 'salary', 'gender', 'city', 'date', 'purchase_amount', 'experience', 'rating']

### 8. Change Data Type (Float -> Int where applicable)

In [ ]:
for col in df.select_dtypes(include=['float64']).columns:
    # Only convert if values don't have non-zero decimals
    if (df[col] % 1 == 0).all():
        df[col] = df[col].astype(int)

print("Data types after float to int conversion:")
print(df.dtypes)

Data types after float to int conversion:
id                          int64
age                         int64
salary                      int64
gender                     object
city                       object
date               datetime64[ns]
purchase_amount             int64
experience                  int64
rating                    float64
dtype: object

## 🔹 Solving Intermediate Questions

We will perform these operations on our cleaned dataset `df`.

### 1. Select Multiple Columns and Fill Missing Values Together
(Since we already filled missing values earlier, we will demonstrate this by temporarily introducing some nulls and filling them together.)

In [ ]:
# Let's introduce a few temporary NaN values for demonstration
df.iloc[0, 1] = np.nan # age
df.iloc[1, 2] = np.nan # salary

print("Before filling multiple columns:")
display(df.head(3))

# Fill both columns with their respective column means together
df[["age", "salary"]] = df[["age", "salary"]].fillna(df[["age", "salary"]].mean())

print("\nAfter filling:")
display(df.head(3))

Before filling multiple columns:

,id,age,salary,gender,city,date,purchase_amount,experience,rating
0,1,NaN,28000.0,Male,Bangalore,2026-01-05,1250,1,4.20
1,2,25.0,NaN,Female,Bangalore,2026-01-12,2100,2,4.34
2,3,29.0,48000.0,Male,Bangalore,2026-01-20,3500,5,4.10

After filling:

,id,age,salary,gender,city,date,purchase_amount,experience,rating
0,1,32.578947,28000.000000,Male,Bangalore,2026-01-05,1250,1,4.20
1,2,25.000000,63052.631579,Female,Bangalore,2026-01-12,2100,2,4.34
2,3,29.000000,48000.000000,Male,Bangalore,2026-01-20,3500,5,4.10

### 2. Apply Transformation: Increase Salary/Marks by 10%

In [ ]:
# Increasing the 'salary' column by 10%
df["salary"] = df["salary"] * 1.1
display(df[["id", "salary"]].head())

   id        salary
0   1  30800.000000
1   2  69357.894737
2   3  52800.000000
3   4  60500.000000
4   5  46200.000000

### 3. Fix Inconsistent Text: Standardize Text Format

In [ ]:
# Standardizing 'gender' and 'city' to title case (e.g., Male, Bangalore)
df["gender"] = df["gender"].astype(str).str.strip().str.title()
df["city"] = df["city"].astype(str).str.strip().str.title()

display(df[["gender", "city"]].head())

   gender       city
0    Male  Bangalore
1  Female  Bangalore
2    Male  Bangalore
3  Female      Delhi
4    Male  Hyderabad

### 4. Create New Column: High/Low Purchase Amount

In [ ]:
# Let's label purchases above 3000 as 'High' and others as 'Low'
mean_purchase = df["purchase_amount"].mean()
df["purchase_category"] = np.where(df["purchase_amount"] > mean_purchase, "High", "Low")

display(df[["purchase_amount", "purchase_category"]].head())

   purchase_amount purchase_category
0             1250               Low
1             2100               Low
2             3500               Low
3             4200               Low
4             2750               Low

### 5. Filter Data: Salary > 50,000

In [ ]:
# Filtering dataset for rows where salary is greater than 50,000
high_earners = df[df["salary"] > 50000]

print(f"Found {len(high_earners)} rows matching filter:")
display(high_earners)

Found 14 rows matching filter:

,id,age,salary,gender,city,date,purchase_amount,experience,rating,purchase_category
1,2,25.0,69357.894737,Female,Bangalore,2026-01-12,2100,2,4.34,Low
2,3,29.0,52800.000000,Male,Bangalore,2026-01-20,3500,5,4.10,Low
3,4,31.0,60500.000000,Female,Delhi,2026-02-02,4200,7,4.70,Low
5,6,35.0,79200.000000,Female,Pune,2026-02-18,5800,10,4.34,High
7,8,38.0,93500.000000,Female,Mumbai,2026-03-03,7200,13,4.60,High
8,9,42.0,104500.000000,Female,Bangalore,2026-03-11,9100,17,4.40,High
9,10,30.0,57200.000000,Female,Chennai,2026-03-19,3900,6,4.00,Low
11,12,33.0,74800.000000,Female,Delhi,2026-04-04,5100,9,4.90,Low
12,13,45.0,121000.000000,Male,Hyderabad,2026-04-12,12500,20,4.70,High
13,14,28.0,50600.000000,Female,Nagpur,2026-04-20,3200,5,4.10,Low
14,15,36.0,85800.000000,Male,Mumbai,2026-04-28,6500,11,3.70,High
16,17,40.0,99000.000000,Male,Chennai,2026-05-14,8300,15,4.50,High
17,18,32.0,67100.000000,Female,Bangalore,2026-05-22,4600,8,4.20,Low
18,19,48.0,137500.000000,Male,Delhi,2026-06-01,15000,23,4.80,High

### 6. Drop Unnecessary Columns

In [ ]:
# Dropping the 'experience' column as a demonstration
df_dropped = df.drop(columns=["experience"], errors="ignore")

display(df_dropped.head())

,id,age,salary,gender,city,date,purchase_amount,rating,purchase_category
0,1,32.578947,30800.000000,Male,Bangalore,2026-01-05,1250,4.20,Low
1,2,25.000000,69357.894737,Female,Bangalore,2026-01-12,2100,4.34,Low
2,3,29.000000,52800.000000,Male,Bangalore,2026-01-20,3500,4.10,Low
3,4,31.000000,60500.000000,Female,Delhi,2026-02-02,4200,4.70,Low
4,5,27.000000,46200.000000,Male,Hyderabad,2026-02-10,2750,3.90,Low

### 7. Apply One-Hot Encoding

In [ ]:
# One-Hot encode 'gender' and 'city' columns
df_encoded = pd.get_dummies(df, columns=["gender", "city"], drop_first=True)

display(df_encoded.head())

,id,age,salary,date,purchase_amount,experience,rating,purchase_category,gender_Male,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,city_Nagpur,city_Nashik,city_Pune
0,1,32.578947,30800.000000,2026-01-05,1250,1,4.20,Low,True,False,False,False,False,False,False,False
1,2,25.000000,69357.894737,2026-01-12,2100,2,4.34,Low,False,False,False,False,False,False,False,False
2,3,29.000000,52800.000000,2026-01-20,3500,5,4.10,Low,True,False,False,False,False,False,False,False
3,4,31.000000,60500.000000,2026-02-02,4200,7,4.70,Low,False,False,True,False,False,False,False,False
4,5,27.000000,46200.000000,2026-02-10,2750,4,3.90,Low,True,False,False,True,False,False,False,False

### 8. Sort Dataset by Date

In [ ]:
# Sorting the dataset chronologically based on 'date'
df_sorted = df.sort_values(by="date")

display(df_sorted.head())

,id,age,salary,gender,city,date,purchase_amount,experience,rating,purchase_category
0,1,32.578947,30800.000000,Male,Bangalore,2026-01-05,1250,1,4.20,Low
1,2,25.000000,69357.894737,Female,Bangalore,2026-01-12,2100,2,4.34,Low
2,3,29.000000,52800.000000,Male,Bangalore,2026-01-20,3500,5,4.10,Low
3,4,31.000000,60500.000000,Female,Delhi,2026-02-02,4200,7,4.70,Low
4,5,27.000000,46200.000000,Male,Hyderabad,2026-02-10,2750,4,3.90,Low