<a href="https://colab.research.google.com/github/sankalpgp/T170800517_TSNIF_AIML/blob/sankalpgp%2Fv/TNS_Day_6_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📌 Feature Engineering - Introduction

## 🔹 What is Feature Engineering?
Feature Engineering is the process of transforming raw data into useful features that help machine learning models perform better.

👉 In simple terms:
We convert data into a form that machines can understand easily.

---

## 🔹 Why is Feature Engineering Important?
- Improves model accuracy
- Helps in better data understanding
- Removes noise and unnecessary information
- Makes patterns more visible

---

## 🔹 Types of Features

### 1. Numerical Features
- Continuous values
- Example: Age, Salary, Temperature

### 2. Categorical Features
- Labels or categories
- Example: Gender, City, Color

### 3. Text Features
- Words or sentences
- Example: Reviews, Comments

### 4. Date-Time Features
- Time-based data
- Example: Date, Timestamp

---

## 🎯 Goal of Feature Engineering
Convert raw data ➡️ meaningful inputs for ML models

In [ ]:
import pandas as pd
import numpy as np


# Sample dataset
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Gender": ["Female", "Male", "Male"],
    "Salary": [50000, 60000, 70000],
    "Joining_Date": ["2022-01-01", "2021-06-15", "2020-03-20"]
}

df = pd.DataFrame(data)

# Display dataset
df

      Name  Age  Gender  Salary Joining_Date
0    Alice   25  Female   50000   2022-01-01
1      Bob   30    Male   60000   2021-06-15
2  Charlie   35    Male   70000   2020-03-20

In [ ]:
df.dtypes

Name            object
Age              int64
Gender          object
Salary           int64
Joining_Date    object
dtype: object

# 📌 Handling Numerical Data

## 🔹 What is Numerical Data?
Numerical data consists of numbers and can be measured.

👉 Examples:
- Age
- Salary
- Temperature

---

## 🔹 Why do we need to process numerical data?
- Different features may have different scales
- Large values can dominate smaller ones
- Models perform better when data is properly scaled

---

## 🔹 1. Feature Scaling

### 📌 Standardization
- Converts data to mean = 0 and standard deviation = 1

### 📌 Normalization (Min-Max Scaling)
- Scales values between 0 and 1

---

## 🔹 2. Log Transformation
- Used to reduce skewness in data
- Helps in handling large values

---

## 🔹 3. Binning (Discretization)
- Converts continuous values into categories
- Example: Age → Young, Adult, Old

import pandas as pd
import numpy as np

# Sample numerical data
data = {
    "Age": [18, 29, 90, 40, 60],
    "Salary": [20000, 30000, 500000, 80000, 150000]
}

df = pd.DataFrame(data)
df

#Feature Scaling – Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_scaled = df.copy()
df_scaled[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])

df_scaled

      Name       Age  Gender    Salary Joining_Date
0    Alice -1.224745  Female -1.224745   2022-01-01
1      Bob  0.000000    Male  0.000000   2021-06-15
2  Charlie  1.224745    Male  1.224745   2020-03-20

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_normalized = df.copy()
df_normalized[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])

df_normalized

      Name  Age  Gender  Salary Joining_Date
0    Alice  0.0  Female     0.0   2022-01-01
1      Bob  0.5    Male     0.5   2021-06-15
2  Charlie  1.0    Male     1.0   2020-03-20

In [ ]:
# Apply log transformation
df_log = df.copy()
df_log["Salary_Log"] = np.log(df_log["Salary"])

df_log

      Name  Age  Gender  Salary Joining_Date  Salary_Log
0    Alice   25  Female   50000   2022-01-01   10.819778
1      Bob   30    Male   60000   2021-06-15   11.002100
2  Charlie   35    Male   70000   2020-03-20   11.156251

In [ ]:
# Create bins for Age
bins = [0, 20, 40, 100]
labels = ["Young", "Adult", "Senior"]

df["Age_Group"] = pd.cut(df["Age"], bins=bins, labels=labels)

df

      Name  Age  Gender  Salary Joining_Date Age_Group
0    Alice   25  Female   50000   2022-01-01     Adult
1      Bob   30    Male   60000   2021-06-15     Adult
2  Charlie   35    Male   70000   2020-03-20     Adult

# 📌 Handling Categorical Data

## 🔹 What is Categorical Data?
Categorical data represents labels or categories.

👉 Examples:
- Gender (Male/Female)
- City (Mumbai, Delhi, Pune)
- Color (Red, Blue, Green)

---

## 🔹 Why convert categorical data?
Machine Learning models work with numbers, not text.

👉 So we convert categories ➝ numerical form

---

## 🔹 Encoding Techniques

### 1. Label Encoding
- Converts categories into numbers
- Example:
  Male → 0, Female → 1

---

### 2. One-Hot Encoding
- Creates separate columns for each category
- Uses 0 and 1

---

### 3. Ordinal Encoding
- Used when categories have order
- Example:
  Low < Medium < High

---

### 4. Frequency Encoding
- Replace category with its frequency

---

### 5. Target Encoding (Basic Idea)
- Replace category with mean of target variable

In [ ]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E","F"],
    "Gender": ["Male", "Female", "Female", "Male", "B","Female"],
    "City": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi","Delhi"],
    "Performance": ["Low", "Medium", "High", "Medium", "Low","High"]
}

df = pd.DataFrame(data)
df

  Name  Gender    City Performance
0    A    Male  Mumbai         Low
1    B  Female   Delhi      Medium
2    C  Female  Mumbai        High
3    D    Male    Pune      Medium
4    E       B   Delhi         Low
5    F  Female   Delhi        High

##Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender_Label"] = le.fit_transform(df["Gender"])
df["City_Label"] = le.fit_transform(df["City"])

df

  Name  Gender    City Performance  Gender_Label  City_Label
0    A    Male  Mumbai         Low             2           1
1    B  Female   Delhi      Medium             1           0
2    C  Female  Mumbai        High             1           1
3    D    Male    Pune      Medium             2           2
4    E       B   Delhi         Low             0           0
5    F  Female   Delhi        High             1           0

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender_Label"] = le.fit_transform(df["Gender"])
df["City_Label"] = le.fit_transform(df["City"])
df["Performance_Label"] = le.fit_transform(df["Performance"])
df

,Name,Gender,City,Performance,Gender_Label,City_Label,Performance_Label
0,A,Male,Mumbai,Low,2,1,1
1,B,Female,Delhi,Medium,1,0,2
2,C,Female,Mumbai,High,1,1,0
3,D,Male,Pune,Medium,2,2,2
4,E,B,Delhi,Low,0,0,1
5,F,Female,Delhi,High,1,0,0

#odinal encoding

In [ ]:
# Define order
order = {"Low": 3, "Medium": 2, "High": 1}

df["Performance_Ordinal"] = df["Performance"].map(order)
df

,Name,Gender,City,Performance,Gender_Label,City_Label,Performance_Label,Performance_Ordinal
0,A,Male,Mumbai,Low,2,1,1,3
1,B,Female,Delhi,Medium,1,0,2,2
2,C,Female,Mumbai,High,1,1,0,1
3,D,Male,Pune,Medium,2,2,2,2
4,E,B,Delhi,Low,0,0,1,3
5,F,Female,Delhi,High,1,0,0,1

In [ ]:
#Frequency Encoding
freq = df["City"].value_counts()

df["City_Freq"] = df["City"].map(freq)
df

,Name,Gender,City,Performance,Gender_Label,City_Label,Performance_Label,Performance_Ordinal,City_Freq
0,A,Male,Mumbai,Low,2,1,1,3,2
1,B,Female,Delhi,Medium,1,0,2,2,3
2,C,Female,Mumbai,High,1,1,0,1,2
3,D,Male,Pune,Medium,2,2,2,2,1
4,E,B,Delhi,Low,0,0,1,3,3
5,F,Female,Delhi,High,1,0,0,1,3

#Target Encoding

In [ ]:
# Create a dummy target variable
df["Target"] = [0, 1, 1, 0, 1,2]

# Calculate mean target per category
target_mean = df.groupby("City")["Target"].mean()

df["City_Target_Encoded"] = df["City"].map(target_mean)
df

,Name,Gender,City,Performance,Gender_Label,City_Label,Performance_Label,Performance_Ordinal,City_Freq,Target,City_Target_Encoded
0,A,Male,Mumbai,Low,2,1,1,3,2,0,0.500000
1,B,Female,Delhi,Medium,1,0,2,2,3,1,1.333333
2,C,Female,Mumbai,High,1,1,0,1,2,1,0.500000
3,D,Male,Pune,Medium,2,2,2,2,1,0,0.000000
4,E,B,Delhi,Low,0,0,1,3,3,1,1.333333
5,F,Female,Delhi,High,1,0,0,1,3,2,1.333333

# 📌 Handling Date & Time Features

## 🔹 What is Date-Time Data?
Date-Time data represents time-related information.

👉 Examples:
- Joining Date
- Timestamp
- Order Date

---

## 🔹 Why use Date-Time Features?
- Helps in finding patterns over time
- Useful in trends, seasonality, and time-based predictions

---

## 🔹 Common Feature Extraction

### 📌 Extract from Date:
- Year
- Month
- Day
- Weekday

---

### 📌 Time-Based Features:
- Hour
- Minute
- Second

---

### 📌 Cyclical Encoding (Basic Idea)
- Some features repeat (like months, days)
- Example:
  December (12) is close to January (1)
- Use Sin & Cos transformation to preserve this pattern

In [ ]:
import pandas as pd

data = {
    "Name": ["A", "B", "C"],
    "Joining_Date": ["2022-01-15", "2021-06-20", "2020-12-05"]
}

df = pd.DataFrame(data)

df.info()
# Convert to datetime
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

df

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          3 non-null      object
 1   Joining_Date  3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          3 non-null      object
 1   Joining_Date  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 180.0+ bytes

In [ ]:
df["Year"] = df["Joining_Date"].dt.year
df["Month"] = df["Joining_Date"].dt.month
df["Day"] = df["Joining_Date"].dt.day
df["dayname"] = df["Joining_Date"].dt.day_name()

df

  Name Joining_Date  Year  Month  Day   dayname
0    A   2022-01-15  2022      1   15  Saturday
1    B   2021-06-20  2021      6   20    Sunday
2    C   2020-12-05  2020     12    5  Saturday

In [ ]:

df["Full_DateTime"] = pd.to_datetime([
    "2022-01-15 10:30:00",
    "2021-06-20 14:45:00",
    "2020-12-05 08:15:00"
])

df["Hour"] = df["Full_DateTime"].dt.hour
df["Minute"] = df["Full_DateTime"].dt.minute

# 📌 Feature Creation

## 🔹 What is Feature Creation?
Feature Creation means creating new features from existing data to improve model performance.

👉 In simple terms:
We make new useful columns from old ones.

---

## 🔹 Why is it important?
- Helps model learn better patterns
- Adds more meaningful information
- Improves accuracy

---

## 🔹 Types of Feature Creation

### 📌 1. Mathematical Transformations
- Addition, subtraction, multiplication
- Example: Total = Price × Quantity

---

### 📌 2. Combining Features
- Merge two columns into one
- Example: First Name + Last Name

---

### 📌 3. Extracting Information
- From text or existing columns
- Example: Email → Domain

---

### 📌 4. Domain-Based Features (Basic Idea)
- Based on real-world knowledge
- Example: BMI = Weight / Height²

In [ ]:
import pandas as pd

data = {
    "Name": ["A", "B", "C"],
    "Price": [100, 200, 150],
    "Quantity": [2, 3, 5],
    "First_Name": ["John", "Jane", "Sam"],
    "Last_Name": ["Doe", "Smith", "Brown"],
    "Email": ["john@gmail.com", "jane@yahoo.com", "sam@outlook.com"]
}

df = pd.DataFrame(data)
df

  Name  Price  Quantity First_Name Last_Name            Email
0    A    100         2       John       Doe   john@gmail.com
1    B    200         3       Jane     Smith   jane@yahoo.com
2    C    150         5        Sam     Brown  sam@outlook.com

#Mathematical feature extraction

In [ ]:
# Create Total Price
df["Total_Price"] = df["Price"] * df["Quantity"]

df

  Name  Price  Quantity First_Name Last_Name            Email  Total_Price
0    A    100         2       John       Doe   john@gmail.com          200
1    B    200         3       Jane     Smith   jane@yahoo.com          600
2    C    150         5        Sam     Brown  sam@outlook.com          750

In [ ]:
# Full Name
df["Full_Name"] = df["First_Name"] + " " + df["Last_Name"]

df

  Name  Price  Quantity First_Name Last_Name            Email   Full_Name
0    A    100         2       John       Doe   john@gmail.com    John Doe
1    B    200         3       Jane     Smith   jane@yahoo.com  Jane Smith
2    C    150         5        Sam     Brown  sam@outlook.com   Sam Brown

In [ ]:
# Extract email domain
df["Email_Domain"] = df["Email"].apply(lambda x: x.split("@")[1])

df

,Name,Price,Quantity,First_Name,Last_Name,Email,Total_Price,Full_Name,Email_Domain
0,A,100,2,John,Doe,john@gmail.com,200,John Doe,gmail.com
1,B,200,3,Jane,Smith,jane@yahoo.com,600,Jane Smith,yahoo.com
2,C,150,5,Sam,Brown,sam@outlook.com,750,Sam Brown,outlook.com

In [ ]:
# Add sample data
df["Weight"] = [60, 70, 80]   # kg
df["Height"] = [1.6, 1.7, 1.8]  # meters

# BMI Formula
df["BMI"] = df["Weight"] / (df["Height"] ** 2)

df

,Name,Price,Quantity,First_Name,Last_Name,Email,Total_Price,Full_Name,Email_Domain,Weight,Height,BMI
0,A,100,2,John,Doe,john@gmail.com,200,John Doe,gmail.com,60,1.6,23.437500
1,B,200,3,Jane,Smith,jane@yahoo.com,600,Jane Smith,yahoo.com,70,1.7,24.221453
2,C,150,5,Sam,Brown,sam@outlook.com,750,Sam Brown,outlook.com,80,1.8,24.691358

# 📌 Feature Selection

## 🔹 What is Feature Selection?
Feature Selection means selecting the most important features for the model and removing unnecessary ones.

👉 In simple terms:
Keep useful columns, remove useless ones.

---

## 🔹 Why is it important?
- Reduces complexity
- Improves model performance
- Reduces overfitting
- Faster training

---

## 🔹 Types of Feature Selection

### 📌 1. Filter Methods
- Based on statistical measures
- Example: Correlation

---

### 📌 2. Wrapper Methods (Basic Idea)
- Try different combinations of features
- Select best performing set

---

### 📌 3. Embedded Methods
- Feature selection happens during model training
- Example: Feature importance

---

In [ ]:
import pandas as pd

data = {
    "Age": [25, 30, 35, 40, 45],
    "Salary": [30000, 40000, 50000, 60000, 70000],
    "Experience": [1, 3, 5, 7, 9],
    "Purchased": [0, 0, 0, 0, 1]  # Target variable
}

df = pd.DataFrame(data)
df

df.corr()

                 Age    Salary  Experience  Purchased
Age         1.000000  1.000000    1.000000   0.866025
Salary      1.000000  1.000000    1.000000   0.866025
Experience  1.000000  1.000000    1.000000   0.866025
Purchased   0.866025  0.866025    0.866025   1.000000

In [ ]:
corr_with_target = df.corr()["Purchased"]

corr_with_target

Age           0.866025
Salary        0.866025
Experience    0.866025
Purchased     1.000000
Name: Purchased, dtype: float64

In [ ]:
df_selected = df.drop(columns=["Purchased"])  # just for demo

df_selected

   Age  Salary  Experience
0   25   30000           1
1   30   40000           3
2   35   50000           5
3   40   60000           7
4   45   70000           9

# 📌 Handling Outliers

## 🔹 What are Outliers?
Outliers are data points that are very different from the rest of the data.

👉 Example:
Most salaries = 30k–50k  
One salary = 5,00,000 → Outlier

---

## 🔹 Why handle outliers?
- Can distort analysis
- Affects model performance
- Leads to incorrect predictions

---

## 🔹 Detection Methods

### 📌 1. IQR (Interquartile Range)
- Based on quartiles (Q1, Q3)

---

### 📌 2. Z-Score
- Based on standard deviation

---

### 📌 3. Visualization
- Boxplot
- Scatter plot

---

## 🔹 Treatment Methods

- Remove outliers
- Cap values (limit max/min)
- Transform data (log)

In [ ]:
import pandas as pd

data = {
    "Salary": [30000, 35000, 40000, 45000, 50000, 1000000,]  # Outlier present
}

df = pd.DataFrame(data)
df

    Salary
0    30000
1    35000
2    40000
3    45000
4    50000
5  1000000

In [ ]:
import pandas as pd

data = {
    "Salary": [30000, 35000, 40000, 2000, 45000, 50000, 1000000]  # Outlier present
}

df = pd.DataFrame(data)
df

    Salary
0    30000
1    35000
2    40000
3     2000
4    45000
5    50000
6  1000000

In [ ]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

lower_bound, upper_bound

# Detect outliers
outliers = df[(df["Salary"] < lower_bound) | (df["Salary"] > upper_bound)]

print(outliers)

    Salary
3     2000
6  1000000

In [ ]:
df_no_outliers = df[(df["Salary"] >= lower_bound) & (df["Salary"] <= upper_bound)]
df_no_outliers

   Salary
0   30000
1   35000
2   40000
4   45000
5   50000

In [ ]:
df_capped = df.copy()

df_capped["Salary"] = df_capped["Salary"].clip(lower_bound, upper_bound)
df_capped

   Salary
0   30000
1   35000
2   40000
3   10000
4   45000
5   50000
6   70000

In [ ]:
df_mean_imputed = df.copy()

mean_salary = df_no_outliers["Salary"].mean()
df_mean_imputed.loc[(df_mean_imputed["Salary"] < lower_bound) | (df_mean_imputed["Salary"] > upper_bound), "Salary"] = mean_salary
df_mean_imputed

   Salary
0   30000
1   35000
2   40000
3   40000
4   45000
5   50000
6   40000

##Z- Score method

In [ ]:
from scipy import stats

z_scores = stats.zscore(df["Salary"])
z_scores

array([-0.41871176, -0.40393866, -0.38916557, -0.5014411 , -0.37439247,
       -0.35961937,  2.44726893])

In [ ]:
df_z = df[(abs(z_scores) > 2)]
df_z

    Salary
6  1000000

# 📊 Feature Engineering – Practice Assignment

## 🎯 Objective
Apply feature engineering techniques on a dataset to prepare it for machine learning.

---

## 📁 Dataset
Use any dataset with columns like:
- Age
- Salary
- Gender
- City
- Date
- Purchase_Amount
- Experience
- Rating

---

## 🧠 Instructions
- Perform each task using Python (Pandas, NumPy, Sklearn)
- Write clean and readable code
- Display output after each step

---

# 🔹 Problem 1: Handling Missing Values
Fill missing values:
- Numerical columns → Mean
- Categorical columns → Mode

👉 Output: Dataset with no missing values

---

# 🔹 Problem 2: Feature Scaling
- Apply Standardization on Salary
- Apply Min-Max Scaling on Age

👉 Compare before and after values

---

# 🔹 Problem 3: Encoding Categorical Data
- Apply Label Encoding on Gender
- Apply One-Hot Encoding on City

👉 Output transformed dataset

---

# 🔹 Problem 4: Feature Creation
Create a new column:
Total_Spending = Salary + Purchase_Amount

👉 Analyze how it changes the dataset

---

# 🔹 Problem 5: Date Feature Extraction
From Date column extract:
- Year
- Month
- Day
- Weekday

👉 Add new columns

---

# 🔹 Problem 6: Binning
Convert Age into categories:
- 0–25 → Young
- 26–45 → Adult
- 46+ → Senior

👉 Create Age_Group column

---

# 🔹 Problem 7: Outlier Detection
Detect outliers in Salary using IQR method

👉 Display only outlier rows

---

# 🔹 Problem 8: Feature Interaction
Create a new feature:
Experience_Salary = Experience * Salary

👉 Explain its importance

---

# 🔹 Problem 9: Feature Selection
- Find correlation of all features with Purchase_Amount
- Drop least important feature

👉 Show final dataset

---

#
- Ensure all outputs are visible

## 📁 Dataset

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Saving main.csv to main.csv
User uploaded file "main.csv" with length 1068 bytes

# 🔹 Problem 1: Handling Missing Values
Fill missing values:
- Numerical columns → Mean
- Categorical columns → Mode

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("main.csv")

In [ ]:
df

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating
0,1,22,28000.0,Male,Pune,2026-01-05,1250.0,1.0,4.2
1,2,25,35000.0,Female,Mumbai,12/01/2026,2100.0,2.0,4.5
2,3,29,48000.0,Male,Bangalore,2026-01-20,3500.0,5.0,4.1
3,4,31,55000.0,Female,Delhi,2026-02-02,4200.0,7.0,4.7
4,5,27,42000.0,Male,Hydrabad,2026-02-10,2750.0,4.0,3.9
5,6,35,72000.0,Female,Pune,2026-02-18,5800.0,10.0,4.8
6,7,24,NaN,Male,Nashik,2026-02-25,1800.0,2.0,3.8
7,8,38,85000.0,Female,Mumbai,03-03-2026,7200.0,13.0,4.6
8,9,42,950000.0,Male,Bangalore,2026-03-11,9100.0,17.0,4.4
9,10,30,52000.0,F,Chennai,2026-03-19,3900.0,6.0,4.0
10,11,26,39000.0,Male,Pune,2026-03-27,NaN,3.0,4.3
11,12,33,68000.0,Female,New Delhi,2026-04-04,5100.0,9.0,4.9
12,13,45,110000.0,Male,Hyderabad,2026-04-12,12500.0,20.0,4.7
13,14,28,46000.0,Female,Nagpur,2026-04-20,3200.0,NaN,4.1
14,15,36,78000.0,Male,Mumbai,2026-04-28,6500.0,11.0,3.7
15,16,23,29000.0,Female,Pune,2026-05-06,1450.0,1.0,4.4
16,17,40,90000.0,Male,Chennai,2026-05-14,8300.0,15.0,4.5
17,18,32,61000.0,Female,Banglore,2026-05-22,4600.0,8.0,4.2
18,19,48,125000.0,Male,Delhi,2026-13-01,15000.0,23.0,4.8
19,20,27,44000.0,Female,Nashik,2026-06-09,2900.0,4.0,5.8
20,15,36,78000.0,Male,Mumbai,2026-04-28,6500.0,11.0,3.7

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               21 non-null     int64
 1   Age              21 non-null     int64
 2   Salary           20 non-null     float64
 3   Gender           21 non-null     object
 4   City             21 non-null     object
 5   Date             21 non-null     object
 6   Purchase_Amount  20 non-null     float64
 7   Experience       20 non-null     float64
 8   Rating           21 non-null     float64
dtypes: float64(4), int64(2), object(3)
memory usage: 1.6+ KB

,ID,Age,Salary,Purchase_Amount,Experience,Rating
count,21.000000,21.000000,20.000000,20.00000,20.000000,21.000000
mean,10.714286,32.238095,106750.000000,5382.50000,8.600000,4.385714
std,5.849298,7.334199,200204.599295,3651.25339,6.410518,0.489168
min,1.000000,22.000000,28000.000000,1250.00000,1.000000,3.700000
25%,6.000000,27.000000,43500.000000,2862.50000,3.750000,4.100000
50%,11.000000,31.000000,58000.000000,4400.00000,7.500000,4.400000
75%,15.000000,36.000000,79750.000000,6675.00000,11.500000,4.700000
max,20.000000,48.000000,950000.000000,15000.00000,23.000000,5.800000

In [ ]:
df.isnull().sum()

ID                 0
Age                0
Salary             1
Gender             0
City               0
Date               0
Purchase_Amount    1
Experience         1
Rating             0
dtype: int64

In [ ]:
df = df.drop_duplicates()
df
df.isnull().sum()

ID                 0
Age                0
Salary             1
Gender             0
City               0
Date               0
Purchase_Amount    1
Experience         1
Rating             0
dtype: int64

In [ ]:
df["Gender"] = df["Gender"].replace({
    "M": "Male",
    "F": "Female"
})

In [ ]:
df["City"] = df["City"].replace({
    "Hydrabad": "Hyderabad",
    "Banglore": "Bangalore",
    "New Delhi": "Delhi"
})

In [ ]:
df[["Purchase_Amount","Salary","Experience"]] = df[["Purchase_Amount","Salary","Experience"]].fillna(df[["Purchase_Amount", "Salary","Experience"]].mean())
df.isnull().sum()

ID                 0
Age                0
Salary             0
Gender             0
City               0
Date               0
Purchase_Amount    0
Experience         0
Rating             0
dtype: int64

# 🔹 Problem 2: Feature Scaling
- Apply Standardization on Salary
- Apply Min-Max Scaling on Age

👉 Compare before and after values

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_scaled = df.copy()
df_scaled[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])

df_scaled.head()

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Gender_Label
0,1,-1.379855,-0.411556,Male,Pune,2026-01-05,1250.0,1.0,4.2,1
1,2,-0.967958,-0.375663,Female,Mumbai,12/01/2026,2100.0,2.0,4.5,0
2,3,-0.418762,-0.309004,Male,Bangalore,2026-01-20,3500.0,5.0,4.1,1
3,4,-0.144164,-0.273111,Female,Delhi,2026-02-02,4200.0,7.0,4.7,0
4,5,-0.693360,-0.339770,Male,Hyderabad,2026-02-10,2750.0,4.0,3.9,1

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_normalized = df.copy()
df_normalized[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])

df_normalized.head()

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Gender_Label
0,1,0.000000,0.000000,Male,Pune,2026-01-05,1250.0,1.0,4.2,1
1,2,0.115385,0.007592,Female,Mumbai,12/01/2026,2100.0,2.0,4.5,0
2,3,0.269231,0.021692,Male,Bangalore,2026-01-20,3500.0,5.0,4.1,1
3,4,0.346154,0.029284,Female,Delhi,2026-02-02,4200.0,7.0,4.7,0
4,5,0.192308,0.015184,Male,Hyderabad,2026-02-10,2750.0,4.0,3.9,1

# 🔹 Problem 3: Encoding Categorical Data
- Apply Label Encoding on Gender
- Apply One-Hot Encoding on City

👉 Output transformed dataset

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender_Label"] = le.fit_transform(df["Gender"])

df.head()

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Gender_Label
0,1,22,28000.0,Male,Pune,2026-01-05,1250.0,1.0,4.2,1
1,2,25,35000.0,Female,Mumbai,12/01/2026,2100.0,2.0,4.5,0
2,3,29,48000.0,Male,Bangalore,2026-01-20,3500.0,5.0,4.1,1
3,4,31,55000.0,Female,Delhi,2026-02-02,4200.0,7.0,4.7,0
4,5,27,42000.0,Male,Hyderabad,2026-02-10,2750.0,4.0,3.9,1

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

encoded = encoder.fit_transform(df[["City"]])

df.head()

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Gender_Label
0,1,22,28000.0,Male,Pune,2026-01-05,1250.0,1.0,4.2,1
1,2,25,35000.0,Female,Mumbai,12/01/2026,2100.0,2.0,4.5,0
2,3,29,48000.0,Male,Bangalore,2026-01-20,3500.0,5.0,4.1,1
3,4,31,55000.0,Female,Delhi,2026-02-02,4200.0,7.0,4.7,0
4,5,27,42000.0,Male,Hyderabad,2026-02-10,2750.0,4.0,3.9,1

# 🔹 Problem 4: Feature Creation
Create a new column:
Total_Spending = Salary + Purchase_Amount

👉 Analyze how it changes the dataset

In [ ]:

df["Total_Spending"] = df["Salary"] * df["Purchase_Amount"]

df.head()

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Gender_Label,Total_Spending
0,1,22,28000.0,Male,Pune,2026-01-05,1250.0,1.0,4.2,1,35000000.0
1,2,25,35000.0,Female,Mumbai,12/01/2026,2100.0,2.0,4.5,0,73500000.0
2,3,29,48000.0,Male,Bangalore,2026-01-20,3500.0,5.0,4.1,1,168000000.0
3,4,31,55000.0,Female,Delhi,2026-02-02,4200.0,7.0,4.7,0,231000000.0
4,5,27,42000.0,Male,Hyderabad,2026-02-10,2750.0,4.0,3.9,1,115500000.0

# 🔹 Problem 5: Date Feature Extraction
From Date column extract:
- Year
- Month
- Day
- Weekday

👉 Add new columns

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce", dayfirst=False)

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Weekday"] = df["Date"].dt.day_name()

df.head()

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Gender_Label,Total_Spending,Year,Month,Day,Weekday
0,1,22,28000.0,Male,Pune,2026-01-05,1250.0,1.0,4.2,1,35000000.0,2026.0,1.0,5.0,Monday
1,2,25,35000.0,Female,Mumbai,NaT,2100.0,2.0,4.5,0,73500000.0,NaN,NaN,NaN,NaN
2,3,29,48000.0,Male,Bangalore,2026-01-20,3500.0,5.0,4.1,1,168000000.0,2026.0,1.0,20.0,Tuesday
3,4,31,55000.0,Female,Delhi,2026-02-02,4200.0,7.0,4.7,0,231000000.0,2026.0,2.0,2.0,Monday
4,5,27,42000.0,Male,Hyderabad,2026-02-10,2750.0,4.0,3.9,1,115500000.0,2026.0,2.0,10.0,Tuesday

# 🔹 Problem 6: Binning
Convert Age into categories:
- 0–25 → Young
- 26–45 → Adult
- 46+ → Senior

👉 Create Age_Group column

In [ ]:

bins = [0, 20, 40, 100]
labels = ["Young", "Adult", "Senior"]

df["Age_Group"] = pd.cut(df["Age"], bins=bins, labels=labels)

df.head()

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Gender_Label,Total_Spending,Year,Month,Day,Weekday,Age_Group
0,1,22,28000.0,Male,Pune,2026-01-05,1250.0,1.0,4.2,1,35000000.0,2026.0,1.0,5.0,Monday,Adult
1,2,25,35000.0,Female,Mumbai,NaT,2100.0,2.0,4.5,0,73500000.0,NaN,NaN,NaN,NaN,Adult
2,3,29,48000.0,Male,Bangalore,2026-01-20,3500.0,5.0,4.1,1,168000000.0,2026.0,1.0,20.0,Tuesday,Adult
3,4,31,55000.0,Female,Delhi,2026-02-02,4200.0,7.0,4.7,0,231000000.0,2026.0,2.0,2.0,Monday,Adult
4,5,27,42000.0,Male,Hyderabad,2026-02-10,2750.0,4.0,3.9,1,115500000.0,2026.0,2.0,10.0,Tuesday,Adult

In [ ]:
df.isnull().sum()

ID                 0
Age                0
Salary             0
Gender             0
City               0
Date               3
Purchase_Amount    0
Experience         0
Rating             0
Gender_Label       0
Total_Spending     0
Year               3
Month              3
Day                3
Weekday            3
Age_Group          0
dtype: int64

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")


df["Date"] = df["Date"].fillna(df["Date"].median())


df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Weekday"] = df["Date"].dt.day_name()

# Check missing values
print(df.isnull().sum())

ID                 0
Age                0
Salary             0
Gender             0
City               0
Date               0
Purchase_Amount    0
Experience         0
Rating             0
Gender_Label       0
Total_Spending     0
Year               0
Month              0
Day                0
Weekday            0
Age_Group          0
dtype: int64

# 🔹 Problem 7: Outlier Detection
Detect outliers in Salary using IQR method

👉 Display only outlier rows

In [ ]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

lower_bound, upper_bound


outliers = df[(df["Salary"] < lower_bound) | (df["Salary"] > upper_bound)]

print(outliers)

   ID  Age    Salary Gender       City       Date  Purchase_Amount  \
8   9   42  950000.0   Male  Bangalore 2026-03-11           9100.0

   Experience  Rating  Gender_Label  Total_Spending  Year  Month  Day  \
8        17.0     4.4             1    8.645000e+09  2026      3   11

     Weekday Age_Group
8  Wednesday    Senior

# 🔹 Problem 8: Feature Interaction
Create a new feature:
Experience_Salary = Experience * Salary

👉 Explain its importance

In [ ]:
df["Experience_Salary"] = df["Experience"] * df["Salary"]
df.head()

,ID,Age,Salary,Gender,City,Date,Purchase_Amount,Experience,Rating,Gender_Label,Total_Spending,Year,Month,Day,Weekday,Age_Group,Experience_Salary
0,1,22,28000.0,Male,Pune,2026-01-05,1250.0,1.0,4.2,1,35000000.0,2026,1,5,Monday,Adult,28000.0
1,2,25,35000.0,Female,Mumbai,2026-03-27,2100.0,2.0,4.5,0,73500000.0,2026,3,27,Friday,Adult,70000.0
2,3,29,48000.0,Male,Bangalore,2026-01-20,3500.0,5.0,4.1,1,168000000.0,2026,1,20,Tuesday,Adult,240000.0
3,4,31,55000.0,Female,Delhi,2026-02-02,4200.0,7.0,4.7,0,231000000.0,2026,2,2,Monday,Adult,385000.0
4,5,27,42000.0,Male,Hyderabad,2026-02-10,2750.0,4.0,3.9,1,115500000.0,2026,2,10,Tuesday,Adult,168000.0

## 🔹 Why is it important?
- Helps model learn better patterns
- Adds more meaningful information
- Improves accuracy

# 🔹 Problem 9: Feature Selection
- Find correlation of all features with Purchase_Amount
- Drop least important feature

👉 Show final dataset

In [ ]:
corr_with_target = df.corr(numeric_only=True)["Purchase_Amount"]

print(corr_with_target)

ID                   0.413057
Age                  0.959539
Salary               0.348428
Purchase_Amount      1.000000
Experience           0.960215
Rating               0.243660
Gender_Label         0.360238
Total_Spending       0.468064
Year                      NaN
Month                0.147836
Day                  0.215715
Experience_Salary    0.437511
Name: Purchase_Amount, dtype: float64

In [ ]:
df_selected = df.drop(columns=["Purchase_Amount"])  # just for demo

df_selected.head()

,ID,Age,Salary,Gender,City,Date,Experience,Rating,Gender_Label,Total_Spending,Year,Month,Day,Weekday,Age_Group,Experience_Salary
0,1,22,28000.0,Male,Pune,2026-01-05,1.0,4.2,1,35000000.0,2026,1,5,Monday,Adult,28000.0
1,2,25,35000.0,Female,Mumbai,2026-03-27,2.0,4.5,0,73500000.0,2026,3,27,Friday,Adult,70000.0
2,3,29,48000.0,Male,Bangalore,2026-01-20,5.0,4.1,1,168000000.0,2026,1,20,Tuesday,Adult,240000.0
3,4,31,55000.0,Female,Delhi,2026-02-02,7.0,4.7,0,231000000.0,2026,2,2,Monday,Adult,385000.0
4,5,27,42000.0,Male,Hyderabad,2026-02-10,4.0,3.9,1,115500000.0,2026,2,10,Tuesday,Adult,168000.0